name: CI

on:
  push:
  pull_request:
  release:
    types: [published]
  schedule:
    # Daily at 2:21
    - cron: '21 2 * * *'

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version:
          - name: 3.6
            toxenv: py36
          - name: 3.7
            toxenv: py37
          - name: 3.8
            toxenv: py38
          - name: 3.8
            toxenv: build
          - name: 3.8
            toxenv: readme
          - name: 3.8
            toxenv: safety
          - name: 3.8
            toxenv: secrets
          - name: 3.8
            toxenv: style

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version.name }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version.name }}
    - name: Ensure we have new enough versions to respect python_version
      run: python -m pip install -U pip setuptools
    - name: Install tox
      run: python -m pip install tox
    - name: Run tox
      run: python -m tox -e "${{ matrix.python-version.toxenv }}"
